<a href="https://colab.research.google.com/github/Christopher-P-Moon/Eddy_Tracking_FLKeys/blob/main/MUNSTER_NCFILES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install netcdf4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 102.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 54.8 MB/s eta 0:00:00


In [4]:
from netCDF4 import Dataset as NetCDFFile
import matplotlib.pyplot as plt
import numpy as np
import glob
import os
import xarray as xr

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from netCDF4 import Dataset
file_path = '/content/drive/MyDrive/Eddie_data/01:2021/MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc'
file = Dataset('/content/drive/MyDrive/Eddie_data/01:2021/MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc', 'r') # 'r' for read mode

In [ ]:
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24.0, 26.0

eddy_data_dir = '/content/drive/MyDrive/Eddie_data/01:2021/'

# Get a list of all nc files in the directory
nc_files = glob.glob(os.path.join(eddy_data_dir, '*.nc'))

# Iterate through each nc file
for file_path in nc_files:
    try:
        ds = xr.open_dataset(file_path)

        # Assuming 'latitude' and 'longitude' are the coordinate variables
        latitude = ds['latitude']
        longitude = ds['longitude']

        # Find indices within the Florida Keys bounding box
        lat_indices = np.where((latitude >= lat_min) & (latitude <= lat_max))[0]
        lon_indices = np.where((longitude >= lon_min) & (longitude <= lon_max))[0]

        # Iterate through the time dimension (assuming 'time' is the time variable)
        if 'time' in ds.variables:
            for t in range(len(ds['time'])):
                # Select the data for the current time step
                ds_time = ds.isel(time=t)

                # Check for 'label_anti' and 'label_cyclo' within the Florida Keys region
                if 'label_anti' in ds_time.variables:
                    label_anti_data = ds_time['label_anti'].values

                    # Extract eddy labels within the Florida Keys region
                    anti_eddy_labels = label_anti_data[np.ix_(lat_indices, lon_indices)]

                    # Get unique non-zero labels (0 typically represents no eddy)
                    unique_anti_labels = np.unique(anti_eddy_labels[anti_eddy_labels != 0])

                    if len(unique_anti_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Anti-cyclonic eddy labels in Florida Keys:", unique_anti_labels)

                if 'label_cyclo' in ds_time.variables:
                    label_cyclo_data = ds_time['label_cyclo'].values

                    # Extract eddy labels within the Florida Keys region
                    cyclo_eddy_labels = label_cyclo_data[np.ix_(lat_indices, lon_indices)]

                    # Get unique non-zero labels (0 typically represents no eddy)
                    unique_cyclo_labels = np.unique(cyclo_eddy_labels[cyclo_eddy_labels != 0])

                    if len(unique_cyclo_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Cyclonic eddy labels in Florida Keys:", unique_cyclo_labels)


        ds.close()
    except Exception as e:
        print("Error processing file {file_path}: {e}")

In [ ]:
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24, 26.0

eddy_data_dir = '/content/drive/MyDrive/Eddie_data/01:2021/'

nc_files = glob.glob(os.path.join(eddy_data_dir, '*.nc'))


for file_path in nc_files:
  try:
        ds = xr.open_dataset(file_path)
        latitude = ds['latitude']
        longitude = ds['longitude']
        lat_indices = np.where((latitude >= lat_min) & (latitude <= lat_max))[0]
        lon_indices = np.where((longitude >= lon_min) & (longitude <= lon_max))[0]


        if 'time' in ds.variables:
            for t in range(len(ds['time'])):
                # Select the data for the current time step
                ds_time = ds.isel(time=t)

                # Check for 'label_anti' and 'label_cyclo' within the Florida Keys region
                if 'Label_anti' in ds_time.variables:
                    label_anti_data = ds_time['Label_anti'].values
                    anti_eddy_labels = label_anti_data[np.ix_(lat_indices, lon_indices)]
                    unique_anti_labels = np.unique(anti_eddy_labels[anti_eddy_labels != 0])

                    if len(unique_anti_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Anti-cyclonic eddy labels in Florida Keys:")
                        for label in unique_anti_labels:
                            print(int(label)) # Print each label as an integer

                if 'Label_cyclo' in ds_time.variables:
                    label_cyclo_data = ds_time['Label_cyclo'].values

                    # Extract eddy labels within the Florida Keys region
                    cyclo_eddy_labels = label_cyclo_data[np.ix_(lat_indices, lon_indices)]

                    # Get unique non-zero labels (0 typically represents no eddy)
                    unique_cyclo_labels = np.unique(cyclo_eddy_labels[cyclo_eddy_labels != 0])

                    if len(unique_cyclo_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Cyclonic eddy labels in Florida Keys:")
                        for label in unique_cyclo_labels:
                            print(int(label)) # Print each label as an integer


        ds.close()
  except Exception as e:
        print("error with path")

File: MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1828
1836
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210102_e20210102.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1856
1865
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210103_e20210103.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1877
1882
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210104_e20210104.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1876
1882
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210105_e20210105.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1898
1903
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210106_e20210106.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1874
1884
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210107_e20210107.nc, Time step: 0
Anti-

In [ ]:
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24, 26.0

eddy_data_dir = '/content/drive/MyDrive/Eddie_data/01:2021/'

nc_files = glob.glob(os.path.join(eddy_data_dir, '*.nc'))

for file_path in nc_files:
    try:
        ds = xr.open_dataset(file_path)
        latitude = ds['latitude']
        longitude = ds['longitude']
        lat_indices = np.where((latitude >= lat_min) & (latitude <= lat_max))[0]
        lon_indices = np.where((longitude >= lon_min) & (longitude <= lon_max))[0]


    if 'time' in ds.variables:
            for t in range(len(ds['time'])):
                # Select the data for the current time step
                ds_time = ds.isel(time=t)if 'Label_cyclo' in ds_time.variables:
                label_cyclo_data = ds_time['Label_cyclo'].values

                    # Extract eddy labels within the Florida Keys region
                cyclo_eddy_labels = label_cyclo_data[np.ix_(lat_indices, lon_indices)]

                    # Get unique non-zero labels (0 typically represents no eddy)
                unique_cyclo_labels = np.unique(cyclo_eddy_labels[cyclo_eddy_labels != 0])

          if len(unique_cyclo_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Cyclonic eddy labels in Florida Keys:")
                        for label in unique_cyclo_labels:
                            print(int(label)) # Print each label as an integer


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 29)

In [ ]:
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24, 26.0

eddy_data_dir = '/content/drive/MyDrive/Eddie_data/01:2021/'

nc_files = glob.glob(os.path.join(eddy_data_dir, '*.nc'))

for file_path in nc_files:
    try:
        ds = xr.open_dataset(file_path)
        latitude = ds['latitude']
        longitude = ds['longitude']
        lat_indices = np.where((latitude >= lat_min) & (latitude <= lat_max))[0]
        lon_indices = np.where((longitude >= lon_min) & (longitude <= lon_max))[0]

        # The indentation for the 'if time' block and subsequent code needs to be corrected
        if 'time' in ds.variables:
            for t in range(len(ds['time'])):
                # Select the data for the current time step
                ds_time = ds.isel(time=t)
                # Correct indentation for the Label_cyclo check
                if 'Label_cyclo' in ds_time.variables:
                    label_cyclo_data = ds_time['Label_cyclo'].values

                    # Extract eddy labels within the Florida Keys region
                    cyclo_eddy_labels = label_cyclo_data[np.ix_(lat_indices, lon_indices)]

                    # Get unique non-zero labels (0 typically represents no eddy)
                    unique_cyclo_labels = np.unique(cyclo_eddy_labels[cyclo_eddy_labels != 0])

                    # Correct indentation for this if statement
                    if len(unique_cyclo_labels) > 0:
                        print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                        print("Cyclonic eddy labels in Florida Keys:")
                        for label in unique_cyclo_labels:
                            print(int(label)) # Print each label as an integer

        # Make sure ds.close() is outside the inner loop but inside the try block
        ds.close()
    except Exception as e:
        print(f"error with path: {file_path}, Error: {e}") # Include file path and error in message

File: MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc, Time step: 0
Cyclonic eddy labels in Florida Keys:
1967
error with path: /content/drive/MyDrive/Eddie_data/01:2021/MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc, Error: cannot convert float NaN to integer
File: MUNSTER_v1_eddyident_multi_global_daily_s20210102_e20210102.nc, Time step: 0
Cyclonic eddy labels in Florida Keys:
error with path: /content/drive/MyDrive/Eddie_data/01:2021/MUNSTER_v1_eddyident_multi_global_daily_s20210102_e20210102.nc, Error: cannot convert float NaN to integer
File: MUNSTER_v1_eddyident_multi_global_daily_s20210103_e20210103.nc, Time step: 0
Cyclonic eddy labels in Florida Keys:
1914
error with path: /content/drive/MyDrive/Eddie_data/01:2021/MUNSTER_v1_eddyident_multi_global_daily_s20210103_e20210103.nc, Error: cannot convert float NaN to integer


In [ ]:
ds = xr.open_dataset(file_path)

#range for the Florida Keys
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24.0, 26.0

# Find eddy indices within the specified longitude and latitude range
eddies_in_keys = ds.where(
    (ds.longitude >= lon_min) & (ds.longitude <= lon_max) &
    (ds.latitude >= lat_min) & (ds.latitude <= lat_max),
    drop=True
)

# Extract eddy
anti_eddy_numbers_in_keys = eddies_in_keys['Label_anti'].values

# Print the numbers of the eddies
print("AntiCyclonic Eddy numbers going through the Florida Keys:")
for eddy_number in np.unique(anti_eddy_numbers_in_keys):
    # Exclude NaN values which might result from the .where() operation
    if not np.isnan(eddy_number):
        print(int(eddy_number))

cycl_eddy_numbers_in_keys = eddies_in_keys['Label_cyclo'].values

# Print the  numbers of the eddies
print("Cyclonic Eddy numbers going through the Florida Keys:")
for eddy_number in np.unique(cycl_eddy_numbers_in_keys):
    # Exclude NaN values which might result from the .where() operation
    if not np.isnan(eddy_number):
        print(int(eddy_number))


ds.close()


AntiCyclonic Eddy numbers going through the Florida Keys:
1828
1836
Cyclonic Eddy numbers going through the Florida Keys:
1967


In [ ]:
# Open the dataset again to access eddy properties
ds = xr.open_dataset(file_path)

print("\nAnticyclonic Eddy Properties in the Florida Keys:")
for eddy_label in np.unique(anti_eddy_numbers_in_keys):
    if not np.isnan(eddy_label):
        eddy_data = ds.where(ds.Label_anti == eddy_label, drop=True)
        if eddy_data.sizes['time'] > 0: # Check if there's data for this eddy
            print(f"  Eddy Label: {int(eddy_label)}")
            # Take the first time step's values as an example, or you could average
            print(f"    Latitude: {eddy_data['latitude'].values[0]}")
            print(f"    Longitude: {eddy_data['longitude'].values[0]}")
            print(f"    Mean SST/CE_mean_SST(K): {eddy_data['anticyclonic_mean_sst'].values[0]}")
            print(f"    Mean SSS(PSU): {eddy_data['anticyclonic_mean_sss'].values[0]}")
            print(f"    Mean EKE(m^2 s^-2): {eddy_data['anticyclonic_mean_eke'].values[0]}")
            print(f"    Mean Chla mg m^-3: {eddy_data['anticyclonic_mean_chla'].values[0]}")
            print(f"    Radius(m): {eddy_data['anticyclonic_radius'].values[0]}")
            print(f"    Amplitude(m): {eddy_data['anticyclonic_amplitude'].values[0]}")

ds.close()



Anticyclonic Eddy Properties in the Florida Keys:
  Eddy Label: 1828
    Latitude: 23.625
    Longitude: -82.875
    Mean SST/CE_mean_SST(K): [[[      nan 274.94623 274.94623       nan       nan       nan]
  [274.94623 274.94623 274.94623 274.94623 274.94623       nan]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623       nan]]]
    Mean SSS(PSU): [[[     nan 34.52108 34.52108      nan      nan      nan]
  [34.52108 34.52108 34.52108 34.52108 34.52108      nan]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108      nan]]]
    Mean EKE(m^2 s^-2): [[[       nan 0.00584956 0.00584956        nan        nan        nan]
  [0.005

with fully merged dataset, should be easier to just single out all of the eddies in the area and go from there

1: read into each netcdf file and pull lon/lat data of all the eddies on globe ~ try to filter to specific lon/lat coordinates
2: Print the number of the eddy that passes through the lon lat box and save to a csv/document, note the file that it came from
3: save info of the eddies; lat/lon, ae_mean_ssst/ce_mean_sst, _mean_sss, _mean_eke, _mean_chla, _radius, _amplitude

1: plot each eddies plot along the FC/LC, plot daily temperature changes of each eddy as they go through the designated lat lon
2: tbd




#compat='override'

In [ ]:
ds = xr.open_dataset(file_path)

#range for the Florida Keys
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24.0, 26.0

# Find eddy indices within the specified longitude and latitude range
eddies_in_keys = ds.where(
    (ds.longitude >= lon_min) & (ds.longitude <= lon_max) &
    (ds.latitude >= lat_min) & (ds.latitude <= lat_max),
    drop=True)


# Extract the eddy number
anti_eddy_numbers_in_keys = eddies_in_keys['Label_anti'].values

# Print the specific number of the anitcyclonic eddies
print("AntiCyclonic Eddy numbers going through the Florida Keys:")
for eddy_number in np.unique(anti_eddy_numbers_in_keys):
    # Exclude NaN values which might result from the .where() operation
    if not np.isnan(eddy_number):
        print(int(eddy_number))

cycl_eddy_numbers_in_keys = eddies_in_keys['Label_cyclo'].values

# Print the numbers of the cyclonic eddies
print("Cyclonic Eddy numbers going through the Florida Keys:")
for eddy_number in np.unique(cycl_eddy_numbers_in_keys):
    # Exclude NaN values which might result from the .where() operation
    if not np.isnan(eddy_number):
        print(int(eddy_number))


ds.close()


AntiCyclonic Eddy numbers going through the Florida Keys:
1828
1836
Cyclonic Eddy numbers going through the Florida Keys:
1967


In [ ]:

#this code block reads out AE eddies in the area and their properties
ds = xr.open_dataset(file_path)

print("\nAnticyclonic Eddy Properties in the Florida Keys:")
for eddy_label in np.unique(anti_eddy_numbers_in_keys):
    if not np.isnan(eddy_label):
        eddy_data = ds.where(ds.Label_anti == eddy_label, drop=True)
        if eddy_data.sizes['time'] > 0: # Check if there's data for this eddy
            print(f"  Eddy Label: {int(eddy_label)}")
            # Take the first time step's values as an example, or you could average
            print(f"    Latitude: {eddy_data['latitude'].values[0]}")
            print(f"    Longitude: {eddy_data['longitude'].values[0]}")
            print(f"    Mean SST/CE_mean_SST(K): {eddy_data['anticyclonic_mean_sst'].values[0]}")
            print(f"    Mean SSS(PSU): {eddy_data['anticyclonic_mean_sss'].values[0]}")
            print(f"    Mean EKE(m^2 s^-2): {eddy_data['anticyclonic_mean_eke'].values[0]}")
            print(f"    Mean Chla mg m^-3: {eddy_data['anticyclonic_mean_chla'].values[0]}")
            print(f"    Radius(m): {eddy_data['anticyclonic_radius'].values[0]}")
            print(f"    Amplitude(m): {eddy_data['anticyclonic_amplitude'].values[0]}")

ds.close()


Anticyclonic Eddy Properties in the Florida Keys:
  Eddy Label: 1828
    Latitude: 23.625
    Longitude: -82.875
    Mean SST/CE_mean_SST(K): [[[      nan 274.94623 274.94623       nan       nan       nan]
  [274.94623 274.94623 274.94623 274.94623 274.94623       nan]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623 274.94623]
  [274.94623 274.94623 274.94623 274.94623 274.94623       nan]]]
    Mean SSS(PSU): [[[     nan 34.52108 34.52108      nan      nan      nan]
  [34.52108 34.52108 34.52108 34.52108 34.52108      nan]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108 34.52108]
  [34.52108 34.52108 34.52108 34.52108 34.52108      nan]]]
    Mean EKE(m^2 s^-2): [[[       nan 0.00584956 0.00584956        nan        nan        nan]
  [0.005

In [ ]:

ds = xr.open_dataset(file_path)
if 'lat_bnds' in ds.variables:
    lat_bnds = ds['lat_bnds'].values
    print("lat_bnds values:", lat_bnds)
else:
    print("Variable 'lat_bnds' not found in the dataset.")

if 'lon_bnds' in ds.variables:
    lon_bnds = ds['lon_bnds'].values
    print("lon_bnds values:", lon_bnds)
else:
    print("Variable 'lon_bnds' not found in the dataset.")

In [5]:
lon_min, lon_max = -83.0, -80.0
lat_min, lat_max = 24, 26.0

eddy_data_dir = '/content/drive/MyDrive/Eddie_data/01:2021/'

nc_files = glob.glob(os.path.join(eddy_data_dir, '*.nc'))


for file_path in nc_files:
  try:
        ds = xr.open_dataset(file_path)
        latitude = ds['latitude']
        longitude = ds['longitude']
        lat_indices = np.where((latitude >= lat_min) & (latitude <= lat_max))[0]
        lon_indices = np.where((longitude >= lon_min) & (longitude <= lon_max))[0]


        for t in range(len(ds['time'])):
            # Select the data for the current time step
            ds_time = ds.isel(time=t)


            label_anti_data = ds_time['Label_anti'].values
            anti_eddy_labels = label_anti_data[np.ix_(lat_indices, lon_indices)]
            unique_anti_labels = np.unique(anti_eddy_labels[anti_eddy_labels != 0])

            if len(unique_anti_labels) > 0:
                print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                print("Anti-cyclonic eddy labels in Florida Keys:")
                for label in unique_anti_labels:
                    print(int(label))


            label_cyclo_data = ds_time['Label_cyclo'].values
            cyclo_eddy_labels = label_cyclo_data[np.ix_(lat_indices, lon_indices)]
            unique_cyclo_labels = np.unique(cyclo_eddy_labels[cyclo_eddy_labels != 0])

            if len(unique_cyclo_labels) > 0:
                print(f"File: {os.path.basename(file_path)}, Time step: {t}")
                print("Cyclonic eddy labels in Florida Keys:")
                for label in unique_cyclo_labels:
                    print(int(label))


        ds.close()
  except Exception as e:
        print("error with path")

File: MUNSTER_v1_eddyident_multi_global_daily_s20210101_e20210101.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1828
1836
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210102_e20210102.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1856
1865
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210103_e20210103.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1877
1882
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210104_e20210104.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1876
1882
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210105_e20210105.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1898
1903
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210106_e20210106.nc, Time step: 0
Anti-cyclonic eddy labels in Florida Keys:
1874
1884
error with path
File: MUNSTER_v1_eddyident_multi_global_daily_s20210107_e20210107.nc, Time step: 0
Anti-

In [8]:
ds = xr.open_dataset(file_path)
print(ds.variables)

Frozen({'longitude': <xarray.IndexVariable 'longitude' (longitude: 1440)> Size: 6kB
array([-179.875, -179.625, -179.375, ...,  179.375,  179.625,  179.875],
      dtype=float32)
Attributes:
    standard_name:  longitude
    long_name:      longitude
    units:          degrees_east
    axis:           X
    valid_min:      -180.0
    valid_max:      180.0
    bounds:         lon_bnds, 'latitude': <xarray.IndexVariable 'latitude' (latitude: 480)> Size: 2kB
array([-59.875, -59.625, -59.375, ...,  59.375,  59.625,  59.875],
      dtype=float32)
Attributes:
    standard_name:  latitude
    long_name:      latitude
    units:          degrees_north
    axis:           Y
    valid_min:      -90.0
    valid_max:      90.0
    bounds:         lat_bnds, 'time': <xarray.IndexVariable 'time' (time: 1)> Size: 8B
array(['2021-01-31T00:00:00.000000000'], dtype='datetime64[ns]')
Attributes:
    standard_name:  time
    long_name:      time
    axis:           T
    bounds:         time_bnds, 'coord_r